name: dart_set_scraper
description: A sample command-line application.
version: 0.0.1
#homepage: https://www.example.com
#author: ivan koop <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  convert: ^2.0.1
  sqljocky: ^0.14.1
  


dev_dependencies:
  test: ^0.12.0
  
